
ner:
  name: 'Named Entity Recognition'
  gold_standard: 
    raw_file: 'gold_standard/raw/ner.csv'
    processed_file: 'gold_standard/processed/ner.csv'
  tools:
    flair:
      name: 'flair'
      raw_result: 'ner/flair/flair_ner.xlsx'
      processed_result: 'tool_results/ner/flair.csv'
    nlkt:
      name: 'nlkt'
      raw_result: 'ner/nlkt/nltk_ner_uppercased.xlsx'
      processed_result: 'tool_results/ner/nlkt.csv'
    spacy:
      name: 'spacy'
      raw_result: 'ner/spacy/spacy_ner.xlsx'
      processed_result: 'tool_results/ner/spacy.csv'
    stanza:
      name: 'stanza'
      raw_result: 'ner/stanza/stanza_ner.xlsx'
      processed_result: 'tool_results/ner/stanza.csv'
nel:
  name: 'Named Entity Linking'
  gold_standard: 
    raw_file: 'gold_standard/raw/nel.csv'
    processed_file: 'gold_standard/processed/nel.csv'
  tools:
    spacy:
      name: 'spacy'
      raw_result: ''
      processed_result: 'tool_results/nel/spacy.csv'
    blink:
      name: 'blink'
      raw_result: ''
      processed_result: ''
re:
  name: 'Relation Extraction'
  gold_standard: 
    raw_file: 'gold_standard/raw/re.csv'
    processed_file: 'gold_standard/processed/nel.csv'
  tools:
    spacy:
      name: 'spacy'
      raw_result: ''
      processed_result: 'tool_results/nel/spacy.csv'
    blink:
      name: 'blink'
      raw_result: ''
      processed_result: ''
cr:
  name: 'Coreference Resolution'
  gold_standard: 
    raw_file: ''
    processed_file: ''
  tools:
    tool_1:
      name: 'tool_1'
      raw_result: ''
      processed_result: ''
    tools_2:
      name: 'tool_2'
      raw_result: ''
      processed_result: ''
